%macro slc_rmend(return=,resolve=N);                                            
  run;                                                                          
  quit;                                                                         
  data _null_;                                                                  
    infile "c:/temp/rm_pgmx.xml";                                               
    input;                                                                      
    file "c:/temp/rm_pgm.xml";                                                  
    if upcase(substr("&resolve",1,1))="Y" then                                  
       _infile_=resolve(_infile_);                                              
    put _infile_;                                                               
    putlog _infile_;                                                            
  run;                                                                          
  quit;                                                                         
  * EXECUTE THE PYTHON PROGRAM USING DIRECT PYTHON (NOT CONDA RUN);             
  options noxwait noxsync;                                                      
  filename rut pipe "C:\PROGRA~2\Java\jdk1.6.0_45\bin\java.exe -cp C:\PROGRA~2\Rapid-I\RapidMiner5\lib\rapidminer.jar com.rapidminer.RapidMinerCommandLine -f c:\temp\rm_pgm.xml >> c:\temp\rm_pgm.log 2>&1";                                   
  data _null_;                                                                                                                                                                                                                                  
    file print;                                                                                                                                                                                                                                 
    infile rut;                                                                                                                                                                                                                                 
    input;                                                                                                                                                                                                                                      
    put _infile_;                                                                                                                                                                                                                               
    putlog _infile_;                                                                                                                                                                                                                            
  run;                                                                                                                                                                                                                                          
  quit;                                                                                                                                                                                                                                         
  data _null_;                                                                                                                                                                                                                                  
    infile "c:/temp/rm_pgm.log";                                                                                                                                                                                                                
    input;                                                                                                                                                                                                                                      
    putlog _infile_;                                                                                                                                                                                                                            
  run;                                                                                                                                                                                                                                          
  quit;                                                                                                                                                                                                                                         
  %if "&return" ne "" %then %do;                                                                                                                                                                                                                
    filename clp clipbrd;                                                                                                                                                                                                                       
    data _null_;                                                                                                                                                                                                                                
      infile clp;                                                                                                                                                                                                                               
      input;                                                                                                                                                                                                                                    
      putlog "xxxxxx  " _infile_;                                                                                                                                                                                                               
      call symputx("&return.",_infile_,"G");                                                                                                                                                                                                    
    run;                                                                                                                                                                                                                                        
    quit;                                                                                                                                                                                                                                       
  %end;                                                                                                                                                                                                                                         
%mend slc_rmend;                                                                                                                                                                                                                                
