%macro slc_plend(returnvar=N);                                                  
run;quit;                                                                       
data _null_; file  "c:/temp/pl_log.txt"; run;                                   
options noxwait noxsync;                                                        
filename rut pipe "cmd /c c:\strawberry\perl\bin\perl c:/temp/pl_pgm.txt > c:/temp/pl_log.txt";                                                                 
  data _null_;                                                                                                                                                  
    file print;                                                                                                                                                 
    infile rut recfm=v lrecl=32756;                                                                                                                             
    input;                                                                                                                                                      
    put _infile_;                                                                                                                                               
    putlog _infile_;                                                                                                                                            
  run;                                                                                                                                                          
  * use the clipboard to create macro variable;                                                                                                                 
  * you need to use perl write to clipboard prior to this section;                                                                                              
  %if %upcase(%substr(&returnVar.,1,1)) ne N %then %do;                                                                                                         
    filename clp clipbrd ;                                                                                                                                      
    data _null_;                                                                                                                                                
     length txt $200;                                                                                                                                           
     infile clp;                                                                                                                                                
     input;                                                                                                                                                     
     putlog "macro variable &returnVar = " _infile_;                                                                                                            
     call symputx("&returnVar.",_infile_,"G");                                                                                                                  
    run;quit;                                                                                                                                                   
  %end;                                                                                                                                                         
data _null_;                                                                                                                                                    
  file print;                                                                                                                                                   
  infile rut;                                                                                                                                                   
  input;                                                                                                                                                        
  put _infile_;                                                                                                                                                 
  putlog _infile_;                                                                                                                                              
run;quit;                                                                                                                                                       
data _null_;                                                                                                                                                    
  infile "c:/temp/pl_log.txt";                                                                                                                                  
  input;                                                                                                                                                        
  putlog _infile_;                                                                                                                                              
  file print;                                                                                                                                                   
   put _infile_;                                                                                                                                                
run;quit;                                                                                                                                                       
%mend slc_plend;                                                                                                                                                
