%macro slc_pyend(return=,resolve=N);                                            
run;quit;                                                                       
data _null_;                                                                    
  infile "c:/temp/py_pgmx.py";                                                  
  input;                                                                        
  file "c:/temp/py_pgm.py";                                                     
  if upcase(substr("&resolve",1,1))="Y" then                                    
     _infile_=resolve(_infile_);                                                
  put _infile_;                                                                 
  putlog _infile_;                                                              
run;quit;                                                                       
* EXECUTE THE PYTHON PROGRAM;                                                   
options noxwait noxsync;                                                        
filename rut pipe  "d:\Py314\python.exe c:/temp/py_pgm.py 2> c:/temp/py_pgm.log";                                                                               
run;quit;                                                                                                                                                       
data _null_;                                                                                                                                                    
  file print;                                                                                                                                                   
  infile rut;                                                                                                                                                   
  input;                                                                                                                                                        
  put _infile_;                                                                                                                                                 
  putlog _infile_;                                                                                                                                              
run;quit;                                                                                                                                                       
data _null_;                                                                                                                                                    
  infile "c:/temp/py_pgm.log";                                                                                                                                  
  input;                                                                                                                                                        
  putlog _infile_;                                                                                                                                              
run;quit;                                                                                                                                                       
%if "&return" ne ""  %then %do;                                                                                                                                 
  filename clp clipbrd ;                                                                                                                                        
  data _null_;                                                                                                                                                  
   infile clp;                                                                                                                                                  
   input;                                                                                                                                                       
   putlog "xxxxxx  " _infile_;                                                                                                                                  
   call symputx("&return.",_infile_,"G");                                                                                                                       
  run;quit;                                                                                                                                                     
  %end;                                                                                                                                                         
%mend slc_pyend;                                                                                                                                                
