%macro sqlPartition(data,by=);                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                
  (select                                                                                                                                                                                                                                                       
     row_number                                                                                                                                                                                                                                                 
    ,row_number - min(row_number) +1 as partition                                                                                                                                                                                                               
    ,*                                                                                                                                                                                                                                                          
  from                                                                                                                                                                                                                                                          
      (select *, monotonic() as row_number from                                                                                                                                                                                                                 
         (select *, max(%scan(%str(&by),1,%str(,))) as delete from &data group by &by ))                                                                                                                                                                        
  group                                                                                                                                                                                                                                                         
      by &by )                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                
%mend sqlPartition;      
