/* Bart Jablonski <yabwon@GMAIL.COM> */
/* macros */
%macro dynArray(ARRAY, TYPE=8, HASHEXP=8);
  if _N_ = 1 then
  do;
    length _I_ _RC_ 8 _&ARRAY.CELL_ &type. ;
    declare hash &ARRAY.(ordered:"A", hashexp:&HASHEXP.);
    &ARRAY..defineKey("_I_");
    &ARRAY..defineData("_I_","_&ARRAY.CELL_");
    &ARRAY..defineDone();
    &ARRAY..clear();
    declare hiter IT_&ARRAY.("&ARRAY.");
    drop _&ARRAY.CELL_ _I_ _RC_;
  end;
%mend dynArray;
%macro appendTo(ARRAY, VARIABLE);
  call missing(_I_);
  _RC_ = IT_&ARRAY..last();
  _I_ + 1;
  _&ARRAY.CELL_ = &VARIABLE.;
  _RC_ = &ARRAY..replace();
%mend appendTo;
%macro appendBefore(ARRAY, VARIABLE);
  call missing(_I_);
  _RC_ = IT_&ARRAY..first();
  _I_ + (-1);
  _&ARRAY.CELL_ = &VARIABLE.;
  _RC_ = &ARRAY..replace();
%mend appendBefore;
%macro loopOver(ARRAYS);
  %local ARRAY i;
  %let ARRAY = %scan(&ARRAYS., 1);
  _RC_ = IT_&ARRAY..first();
  _RC_ = IT_&ARRAY..prev();
  do while(IT_&ARRAY..next()=0);
    %let i = 2;
    %let ARRAY = %scan(&ARRAYS., &i.);
    %do %while(&ARRAY. ne);
      call missing(_&ARRAY.CELL_);
      _RC_ = &ARRAY..find();
      %let i = %eval(&i.+1);
      %let ARRAY = %scan(&ARRAYS., &i.);
    %end;
/*end;*/
%mend loopOver;
%macro loopEnd;
end;
%mend loopEnd;
%macro getVal(VARIABLE, ARRAY, INDEX);
  call missing(_&ARRAY.CELL_);
  _I_ = &INDEX;
  _RC_ = &ARRAY..find();
  &VARIABLE. = _&ARRAY.CELL_;
%mend getVal;
%macro putVal(ARRAY, INDEX, VARIABLE);
  if not missing(&INDEX.) then
    do;
      _I_ = &INDEX;
      _&ARRAY.CELL_ = &VARIABLE. ;
      _RC_ = &ARRAY..replace();
    end;
%mend putVal;
%macro rangeOf(ARRAY, START=lbound&ARRAY., END=hbound&ARRAY.);
  _RC_ = IT_&ARRAY..first();
  &START. = _I_;
  _RC_ = IT_&ARRAY..last();
  &END. = _I_;
  drop &START. &END.;
%mend rangeOf;
