%macro utl_sqlinsert(dsn,_out_)
   /des="send sql insert code to the log and clipbord paste buffer";
   options ls=256;
   filename tmp temp lrecl=4096;
   ods tagsets.sql file=tmp;
   proc print data=&dsn;
   run;quit;
   ods _all_ close; ** very important;
   data _null_;
   infile tmp end=dne;
   input;
   put _infile_;
   run;quit;
   filename _out_ "&_out_";
   data _null_;
    retain flg 0;
    length once $255 remain $255;
    infile tmp end=dne;
    file _out_;
    input;
    select;
       when (_n_ =1)           leave;
       when (_n_ < 3)  do;
           put _infile_;
           putlog _infile_;
       end;
       when (_infile_=:"Insert into" and flg=0)  do;
          flg=1;
          once=catx(' ',cats(scan(_infile_,1,')'),')'),'VALUES');
          remain=cats(scan(_infile_,2,')'),')');
          put once;
          putlog once;
          *put remain;
          *putlog remain;
       end;
       when (_infile_=:"Insert into") do;
          remain=substr(_infile_,index(_infile_,'Values')+6);
          if not dne then remain=translate(remain,',',';');
          put remain;
          putlog remain;
       end;
       * leave otherwise off to force error;
    end;
   run;quit;
   filename tmp clear;
   ods listing;
   options ls=255;
%mend utl_sqlinsert;
