%macro utl_slc_mend(returnvar=N);                                               
options noxwait noxsync;                                                        
filename rut pipe  "octave-cli c:/temp/m_pgm.m > c:/temp/m_pgm.log";            
run;quit;                                                                       
  data _null_;                                                                  
    file print;                                                                 
    infile rut recfm=v lrecl=32756;                                             
    input;                                                                      
    put _infile_;                                                               
    putlog _infile_;                                                            
  run;                                                                          
  filename ft15f001 clear;                                                      
  * use the clipboard to create macro variable;                                 
  %if &returnVar. ne N %then %do;                                               
    filename clp clipbrd ;                                                      
    data _null_;                                                                
     length txt $200;                                                           
     infile clp;                                                                
     input;                                                                     
     putlog "macro variable &returnVar = " _infile_;                            
     call symputx("&returnVar.",_infile_,"G");                                  
    run;quit;                                                                   
  %end;                                                                         
data _null_;                                                                    
  file print;                                                                   
  infile "c:/temp/m_pgm.log" ;                                                  
  input;                                                                        
  put _infile_;                                                                 
  putlog _infile_;                                                              
run;quit;                                                                       
filename ft15f001 clear;                                                        
%mend utl_slc_mend;                                                             
