%macro utl_pyendx(return=);                                                             
run;quit;                                                                               
data _null_;                                                                            
  infile "c:/temp/py_pgm.pyx";                                                          
  input;                                                                                
  file "c:/temp/py_pgm.py";                                                             
  put _infile_;                                                                         
run;quit;                                                                               
* EXECUTE THE PYTHON PROGRAM;                                                           
options noxwait noxsync;                                                                
filename rut pipe  "d:\Python310\python.exe c:/temp/py_pgm.py 2> c:/temp/py_pgm.log";   
run;quit;                                                                               
data _null_;                                                                            
  file print;                                                                           
  infile rut;                                                                           
  input;                                                                                
  put _infile_;                                                                         
  putlog _infile_;                                                                      
run;quit;                                                                               
data _null_;                                                                            
  infile "c:/temp/py_pgm.log";                                                          
  input;                                                                                
  putlog _infile_;                                                                      
run;quit;                                                                               
%if "&return" ne ""  %then %do;                                                         
  filename clp clipbrd ;                                                                
  data _null_;                                                                          
   infile clp obs=1;                                                                          
   input;                                                                               
   putlog "xxxxxx  " _infile_;                                                          
   call symputx("&return.",_infile_,"G");                                               
  run;quit;                                                                             
  %end;                                                                                 
  filename ft15f001 clear;                                                              
%mend utl_pyendx;                                                                       
