%macro utl_pgend(returnvar=N);
options noxwait noxsync;
  data _null_;
    length cmd $200;
    infile  "c:/temp/pg_pgm.sql";
    file  "c:/temp/pg_pgmx.sql" ;
    input;
    if left(_infile_) =: '-f ' then do;
      cmd=catx(' ','psql -U postgres -d template1',_infile_);
      putlog cmd;
      rc=system(strip(cmd));
    end;
    else do;
       put _infile_;
    end;
  run;quit;
  filename rut pipe  "psql -U postgres -d template1 -f c:/temp/pg_pgmx.sql > c:/temp/pg_pgm.log";
  data _null_;
    file print;
    infile rut recfm=v lrecl=32756;
    input;
    putlog _infile_;
    put _infile_;
  run;
  filename ft15f001 clear;
  * use the clipboard to create macro variable;
  %if %upcase(%substr(&returnVar.,1,1)) ne N %then %do;
    filename clp clipbrd ;
    data _null_;
     length txt $200;
     infile clp;
     input;
     putlog "macro variable &returnVar = " _infile_;
     call symputx("&returnVar.",_infile_,"G");
    run;quit;
  %end;
data _null_;
  file print;
  infile rut;
  input;
  put _infile_;
  putlog _infile_;
run;quit;
data _null_;
  infile "c:/temp/pg_pgm.log";
  input;
  putlog _infile_;
run;quit;
filename ft15f001 clear;
%mend utl_pgend;
