%macro utl_pyend39;                                                                                                                                                                                                                                             
run;quit;                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                
* EXECUTE THE PYTHON PROGRAM;                                                                                                                                                                                                                                   
options noxwait noxsync;                                                                                                                                                                                                                                        
filename rut pipe  "c:\Python39\python.exe c:/temp/py_pgm.py 2> c:/temp/py_pgm.log";                                                                                                                                                                            
run;quit;                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                
data _null_;                                                                                                                                                                                                                                                    
  file print;                                                                                                                                                                                                                                                   
  infile rut;                                                                                                                                                                                                                                                   
  input;                                                                                                                                                                                                                                                        
  put _infile_;                                                                                                                                                                                                                                                 
  putlog _infile_;                                                                                                                                                                                                                                              
run;quit;                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                
data _null_;                                                                                                                                                                                                                                                    
  infile " c:/temp/py_pgm.log";                                                                                                                                                                                                                                 
  input;                                                                                                                                                                                                                                                        
  putlog _infile_;                                                                                                                                                                                                                                              
run;quit;                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                
%mend utl_pyend39;     
