%macro utl_slc_rend(                                                            
   tblinp=d:/sd1/class.sas7bdat                                                 
  ,tblout=class                                                                 
  ,return=N                                                                     
  ,resolve=Y);                                                                  
run;quit;                                                                       
data _null_;                                                                    
  infile "c:/temp/r_pgm.sas";                                                   
  input;                                                                        
  file "c:/temp/r_pgmx.sas";                                                    
  %if &resolve=Y %then %do;                                                     
    _infile_=resolve(_infile_);                                                 
    put _infile_;                                                               
  %end;                                                                         
run;quit;                                                                       
options noxwait noxsync;                                                        
filename rut pipe "D:\r451\bin\r.exe --vanilla --quiet --no-save < c:/temp/r_pgmx.sas";                                                                         
data _null_;                                                                                                                                                    
  file print;                                                                                                                                                   
  infile rut;                                                                                                                                                   
  input;                                                                                                                                                        
  put _infile_;                                                                                                                                                 
  putlog _infile_;                                                                                                                                              
run;quit;                                                                                                                                                       
data _null_;                                                                                                                                                    
  infile " c:/temp/r_pgm.sas";                                                                                                                                  
  input;                                                                                                                                                        
  putlog _infile_;                                                                                                                                              
run;quit;                                                                                                                                                       
%if %upcase(%substr(&return.,1,1)) ne N %then %do;                                                                                                              
  filename clp clipbrd ;                                                                                                                                        
  data _null_;                                                                                                                                                  
   infile clp obs=1;                                                                                                                                            
   input;                                                                                                                                                       
   putlog "xxxxxx  " _infile_;                                                                                                                                  
   call symputx("&return.",_infile_,"G");                                                                                                                       
  run;quit;                                                                                                                                                     
%end;                                                                                                                                                           
filename ft15f001 clear;                                                                                                                                        
filename rut clear;                                                                                                                                             
filename r_pgm clear;                                                                                                                                           
filename tmp temp;                                                                                                                                              
data _null_;                                                                                                                                                    
  file tmp;                                                                                                                                                     
  put "options set=RHOME 'D:\d451';";                                                                                                                           
  put "proc R;";                                                                                                                                                
  put "submit;";                                                                                                                                                
  put "load('d:/wpswrk/workspace.RData')";                                                                                                                      
  put "want";                                                                                                                                                   
  put "ls()";                                                                                                                                                   
  put "endsubmit;";                                                                                                                                             
  put "import r=&tblout data=&tblout;";                                                                                                                         
  put "run;quit;";                                                                                                                                              
run;quit;                                                                                                                                                       
%inc tmp;                                                                                                                                                       
%if &return ne N %then %do;                                                                                                                                     
  filename clp clipbrd ;                                                                                                                                        
  data _null_;                                                                                                                                                  
   infile clp;                                                                                                                                                  
   input;                                                                                                                                                       
   putlog "macro variable &return = " _infile_;                                                                                                                 
   call symputx("&return.",_infile_,"G");                                                                                                                       
  run;quit;                                                                                                                                                     
%end;                                                                                                                                                           
%mend utl_slc_rend;                                                                                                                                             
