%macro utl_psend;
run;quit;
* EXECUTE THE PYTHON PROGRAM;
options noxwait noxsync;
filename rut pipe "powershell.exe -executionpolicy bypass -file c:/temp/ps_pgm.ps1";
run;quit;
data _null_;
  file print;
  infile rut;
  input;
  put _infile_;
  putlog _infile_;
run;quit;
data _null_;
  infile " c:/temp/ps_pgm.log";
  input;
  putlog _infile_;
run;quit;
%mend utl_plend;
